import ThinkoriaFooter from "@/components/ThinkoriaFooter";
/*
 * The Reading Room: About page as the emotional and editorial center of Thinkoria.
 * It should feel like a letter from the room rather than an institutional brochure.
 */
import { ArrowUpRight, BookOpen, Compass, Heart, PenLine } from "lucide-react";
import ThemeToggle from "@/components/ThemeToggle";

export default function About() {
  return <main className="min-h-screen bg-[#F3F0E8] text-[#171614]"><header className="border-b border-[#171614]/15"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 lg:px-12"><a href="/" className="flex items-center gap-3"><img src="/manus-storage/thinkoria-logo_8998c7d8.png" alt="" className="h-9 w-9 object-contain"/><span className="font-serif text-[21px] leading-none tracking-[-0.035em]">Thinkoria</span></a><div className="flex items-center gap-6 font-sans text-[10px] font-semibold uppercase tracking-[0.14em]"><a href="/catalogue" className="hidden sm:block nav-link">Catalogue</a><a href="/club" className="hidden sm:block nav-link">Nagaon Club</a><a href="/forum" className="hidden sm:block nav-link">Forum</a><ThemeToggle /><a href="/submit" className="button-ink">Submit a paper <ArrowUpRight size={14}/></a></div></div></header>
    <section className="mx-auto max-w-[1440px] px-6 pb-20 pt-16 lg:px-12 lg:pb-28 lg:pt-24"><div className="grid gap-12 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><div className="eyebrow"><span className="vermilion-dot"/> About the index</div><h1 className="mt-7 max-w-[850px] font-serif text-6xl leading-[.89] tracking-[-.06em] lg:text-[8.2rem]">A room for ideas that are still <em>becoming.</em></h1></div><p className="max-w-[410px] border-l border-[#171614]/20 pl-6 font-sans text-[15px] leading-7 text-[#171614]/65">Thinkoria began with a simple belief: a serious idea should not have to arrive finished in order to deserve company.</p></div></section>
    <section className="border-y border-[#171614]/15 bg-[#EAE5DA] px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-[.65fr_1.35fr]"><div><div className="citation-mark"><span/><b>TH / ABOUT</b></div><h2 className="mt-7 max-w-[370px] font-serif text-5xl leading-[.92] tracking-[-.045em]">We are building a commons for <em>attention.</em></h2></div><div className="max-w-[710px] space-y-6 font-sans text-[16px] leading-8 text-[#171614]/70"><p><strong>Thinkoria means a place of ideas.</strong> It is a publishing room for thoughts in motion — a space where a question can arrive unfinished, meet another mind, and become clearer through attention.</p><p>There are more ideas in the world than there are rooms willing to hold them. Thinkoria is one such room: independent, interdisciplinary, and open to the work that sits between familiar categories.</p><p>We publish papers, essays, criticism, field notes, and unfinished arguments. We care about the sentence that changes the question, the reference that opens a door, and the generous disagreement that makes a thought stronger.</p><p>Our hope is not to make thinking look polished. It is to make thinking feel possible — in print, on screen, around a table in Nagaon, and in conversations that continue after the page ends.</p></div></div></section>
    <section className="mx-auto max-w-[1440px] px-6 py-20 lg:px-12 lg:py-28"><div className="mb-14 max-w-[530px]"><div className="eyebrow"><span className="vermilion-dot"/> What we hold to</div><h2 className="mt-6 font-serif text-5xl leading-[.94] tracking-[-.045em] lg:text-7xl">A few principles for keeping a room <em>alive.</em></h2></div><div className="grid border-l border-t border-[#171614]/20 sm:grid-cols-2 lg:grid-cols-4">{[[Compass,"Curiosity","We begin with a question, not a conclusion."],[BookOpen,"Careful reading","We believe attention is a form of generosity."],[Heart,"Open company","We make space for different disciplines and different voices."],[PenLine,"Work in motion","We welcome the honest middle of the process — the draft, the doubt, the next version."]].map(([Icon,title,text]) => <div key={title as string} className="border-b border-r border-[#171614]/20 p-6 lg:min-h-[260px]"><Icon size={21} className="text-[#C8472C]"/><h3 className="mt-14 font-serif text-3xl leading-none">{title as string}</h3><p className="mt-4 font-sans text-sm leading-6 text-[#171614]/60">{text as string}</p></div>)}</div></section>
    <section className="bg-[#171614] px-6 py-20 text-[#F3F0E8] lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><div className="eyebrow !text-[#F3F0E8]/60"><span className="vermilion-dot"/> A note to contributors</div><h2 className="mt-6 font-serif text-5xl leading-[.92] tracking-[-.045em] lg:text-7xl">Bring us the work that keeps <em>returning.</em></h2></div><div className="max-w-[520px]"><p className="font-sans text-[15px] leading-7 text-[#F3F0E8]/65">If you have a paper, essay, review, or working thought that wants a wider conversation, send it to us by email. Tell us what the work is trying to find out. We will read it closely.</p><a href="/submit" className="button-vermilion mt-8">Send your work <ArrowUpRight size={15}/></a></div></div></section>
  <ThinkoriaFooter /></main>;
}
