/*
 * The Reading Room: catalogue page as an editorial index, with quiet paper surfaces,
 * citation marks, serif titles, and restrained metadata.
 */
import { ArrowUpRight, Search, SlidersHorizontal } from "lucide-react";

const categories = ["All fields", "Philosophy", "Literature", "Media", "Gaming", "Science", "Technology", "Religion", "Linguistics", "Society", "History", "Art & Design"];
const articles = [
  { id: "CI–014", title: "The politics of being unfinished", author: "Mara Voss", field: "Philosophy", excerpt: "On the ethical value of leaving a question open long enough for another mind to enter it.", date: "18 Aug 2026", views: "1,284" },
  { id: "CI–013", title: "Against frictionless reading", author: "Jon Bell", field: "Media", excerpt: "A small argument for difficulty, annotation, and the productive drag of a page that resists us.", date: "12 Aug 2026", views: "986" },
  { id: "CI–012", title: "The interface as a room", author: "Leila Okafor", field: "Technology", excerpt: "Digital spaces are not neutral containers. They instruct us in how to gather, speak, and stay.", date: "05 Aug 2026", views: "2,106" },
  { id: "CI–011", title: "A grammar for disappearing places", author: "Nadia Rahman", field: "Linguistics", excerpt: "What happens to a language when the place it names is no longer there to answer back?", date: "29 Jul 2026", views: "743" },
  { id: "CI–010", title: "Play is not an escape hatch", author: "Arun Sen", field: "Gaming", excerpt: "Games offer rehearsals for living together: rules, friction, improvisation, and consequence.", date: "21 Jul 2026", views: "1,532" },
  { id: "CI–009", title: "The secular afterlife of ritual", author: "Elena Moritz", field: "Religion", excerpt: "A study of the gestures we keep when the beliefs that once held them have shifted.", date: "14 Jul 2026", views: "612" },
];

export default function Catalogue() {
  return <main className="min-h-screen bg-[#F3F0E8] text-[#171614]"><header className="border-b border-[#171614]/15"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 lg:px-12"><a href="/" className="flex items-center gap-3"><img src="/manus-storage/common-index-mark_234d3c95.png" alt="" className="h-9 w-9 object-contain" /><span className="font-serif text-[21px] leading-none tracking-[-0.035em]">The Common Index</span></a><div className="flex items-center gap-5 font-sans text-[10px] font-semibold uppercase tracking-[0.14em]"><a href="/club" className="hidden sm:block nav-link">Nagaon Club</a><a href="/forum" className="hidden sm:block nav-link">Forum</a><a href="mailto:submit@thecommonindex.org?subject=Paper submission" className="button-ink">Submit a paper <ArrowUpRight size={14}/></a></div></div></header>
    <section className="mx-auto max-w-[1440px] px-6 pb-14 pt-16 lg:px-12 lg:pb-20 lg:pt-24"><div className="eyebrow"><span className="vermilion-dot"/> The catalogue / all fields</div><div className="mt-7 grid gap-9 lg:grid-cols-[1fr_0.72fr] lg:items-end"><h1 className="max-w-[760px] font-serif text-6xl leading-[.9] tracking-[-.055em] lg:text-8xl">A living index of <em>serious work.</em></h1><p className="max-w-[390px] font-sans text-sm leading-7 text-[#171614]/65">Papers, essays, and working thoughts arranged by the questions they keep in motion.</p></div></section>
    <section className="border-y border-[#171614]/15 bg-[#EAE5DA] px-6 py-5 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center gap-3"><SlidersHorizontal size={15} className="mr-1 text-[#C8472C]"/>{categories.map((category, index) => <button key={category} className={`font-sans text-[10px] uppercase tracking-[0.11em] transition-colors hover:text-[#C8472C] ${index === 0 ? "font-semibold text-[#C8472C]" : "text-[#171614]/55"}`}>{category}</button>)}</div></section>
    <section className="mx-auto max-w-[1440px] px-6 py-14 lg:px-12 lg:py-20"><div className="mb-7 flex items-end justify-between border-b border-[#171614]/20 pb-5"><div className="eyebrow"><span className="vermilion-dot"/> 06 papers in view</div><div className="hidden items-center gap-2 font-sans text-[10px] uppercase tracking-[0.12em] text-[#171614]/50 sm:flex"><Search size={14}/> Search coming soon</div></div><div className="border-t border-[#171614]/20">{articles.map((article, index) => <article key={article.id} className={`group grid gap-5 border-b border-[#171614]/20 py-8 lg:grid-cols-[.16fr_1fr_.2fr] lg:gap-10 ${index === 1 ? "lg:pl-8" : index === 4 ? "lg:pr-12" : ""}`}><div className="font-sans text-[10px] uppercase tracking-[0.13em] text-[#171614]/45"><span>{article.id}</span><br/><span className="mt-2 inline-block">{article.field}</span></div><div><h2 className="max-w-[680px] font-serif text-3xl leading-[.98] tracking-[-.025em] transition-colors group-hover:text-[#C8472C] lg:text-4xl">{article.title}</h2><p className="mt-3 max-w-[620px] font-sans text-sm leading-6 text-[#171614]/60">{article.excerpt}</p><p className="mt-4 font-sans text-[10px] uppercase tracking-[0.12em] text-[#171614]/50">{article.author} <span className="mx-2 text-[#C8472C]">/</span> {article.date}</p></div><div className="flex items-end justify-between font-sans text-[10px] uppercase tracking-[0.11em] text-[#171614]/50 lg:flex-col lg:items-end"><span className="inline-flex items-center gap-2"><span className="live-pulse"/> {article.views} views</span><ArrowUpRight size={18} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></div></article>)}</div></section>
    <footer className="border-t border-[#171614]/15 px-6 py-7 lg:px-12"><div className="mx-auto flex max-w-[1440px] justify-between font-sans text-[10px] uppercase tracking-[0.13em] text-[#171614]/50"><span>© The Common Index</span><a href="/">Return home</a></div></footer>
  </main>;
}
