/*
 * The Reading Room: image-led catalogue containers with varied editorial rhythm,
 * warm paper surfaces, and article-first browsing.
 */
import { ArrowUpRight, Search, SlidersHorizontal } from "lucide-react";

const categories = ["All fields", "Philosophy", "Literature", "Media", "Gaming", "Science", "Technology", "Religion", "Linguistics", "Society", "History", "Art & Design"];
const articles = [
  { id: "CI–014", title: "The politics of being unfinished", author: "Mara Voss", field: "Philosophy", excerpt: "On the ethical value of leaving a question open long enough for another mind to enter it.", date: "18 Aug 2026", views: "1,284", image: "/manus-storage/catalogue-philosophy_fec325ad.png" },
  { id: "CI–013", title: "Against frictionless reading", author: "Jon Bell", field: "Media", excerpt: "A small argument for difficulty, annotation, and the productive drag of a page that resists us.", date: "12 Aug 2026", views: "986", image: "/manus-storage/catalogue-media_a6064e08.png" },
  { id: "CI–012", title: "The interface as a room", author: "Leila Okafor", field: "Technology", excerpt: "Digital spaces are not neutral containers. They instruct us in how to gather, speak, and stay.", date: "05 Aug 2026", views: "2,106", image: "/manus-storage/catalogue-technology_1007c3da.png" },
  { id: "CI–011", title: "A grammar for disappearing places", author: "Nadia Rahman", field: "Linguistics", excerpt: "What happens to a language when the place it names is no longer there to answer back?", date: "29 Jul 2026", views: "743", image: "/manus-storage/catalogue-linguistics_1a3e6347.png" },
  { id: "CI–010", title: "Play is not an escape hatch", author: "Arun Sen", field: "Gaming", excerpt: "Games offer rehearsals for living together: rules, friction, improvisation, and consequence.", date: "21 Jul 2026", views: "1,532", image: "/manus-storage/catalogue-gaming_22738702.png" },
  { id: "CI–009", title: "The secular afterlife of ritual", author: "Elena Moritz", field: "Religion", excerpt: "A study of the gestures we keep when the beliefs that once held them have shifted.", date: "14 Jul 2026", views: "612", image: "/manus-storage/catalogue-philosophy_fec325ad.png" },
];

export default function Catalogue() {
  return <main className="min-h-screen bg-[#F3F0E8] text-[#171614]"><header className="border-b border-[#171614]/15"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 lg:px-12"><a href="/" className="flex items-center gap-3"><img src="/manus-storage/common-index-mark_234d3c95.png" alt="" className="h-9 w-9 object-contain"/><span className="font-serif text-[21px] leading-none tracking-[-.035em]">The Common Index</span></a><div className="flex items-center gap-5 font-sans text-[10px] font-semibold uppercase tracking-[.14em]"><a href="/about" className="hidden sm:block nav-link">About</a><a href="/club" className="hidden sm:block nav-link">Nagaon Club</a><a href="/forum" className="hidden sm:block nav-link">Forum</a><a href="mailto:submit@thecommonindex.org?subject=Paper submission" className="button-ink">Submit a paper <ArrowUpRight size={14}/></a></div></div></header>
    <section className="mx-auto max-w-[1440px] px-6 pb-14 pt-16 lg:px-12 lg:pb-20 lg:pt-24"><div className="eyebrow"><span className="vermilion-dot"/> The catalogue / all fields</div><div className="mt-7 grid gap-9 lg:grid-cols-[1fr_.72fr] lg:items-end"><h1 className="max-w-[760px] font-serif text-6xl leading-[.9] tracking-[-.055em] lg:text-8xl">A living index of <em>serious work.</em></h1><p className="max-w-[390px] font-sans text-sm leading-7 text-[#171614]/65">Papers, essays, and working thoughts arranged by the questions they keep in motion.</p></div></section>
    <section className="border-y border-[#171614]/15 bg-[#EAE5DA] px-6 py-5 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center gap-3"><SlidersHorizontal size={15} className="mr-1 text-[#C8472C]"/>{categories.map((category, index) => <button key={category} className={`font-sans text-[10px] uppercase tracking-[.11em] transition-colors hover:text-[#C8472C] ${index === 0 ? "font-semibold text-[#C8472C]" : "text-[#171614]/55"}`}>{category}</button>)}</div></section>
    <section className="mx-auto max-w-[1440px] px-6 py-14 lg:px-12 lg:py-20"><div className="mb-8 flex items-end justify-between border-b border-[#171614]/20 pb-5"><div className="eyebrow"><span className="vermilion-dot"/> 06 papers in view</div><div className="hidden items-center gap-2 font-sans text-[10px] uppercase tracking-[.12em] text-[#171614]/50 sm:flex"><Search size={14}/> Search coming soon</div></div><div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{articles.map((article, index) => <article key={article.id} className={`group overflow-hidden border border-[#171614]/20 bg-[#EAE5DA] transition-transform duration-300 hover:-translate-y-1 ${index === 1 ? "lg:mt-12" : index === 4 ? "lg:-mt-8" : ""}`}><div className="relative aspect-[4/3] overflow-hidden bg-[#D8D0C0]"><img src={article.image} alt={`${article.title} lead image`} className="h-full w-full object-cover grayscale-[10%] transition-transform duration-700 group-hover:scale-[1.035]"/><div className="absolute inset-x-0 top-0 flex justify-between p-4 font-sans text-[10px] uppercase tracking-[.13em] text-[#F3F0E8]"><span className="bg-[#171614]/55 px-2 py-1">{article.id}</span><span className="bg-[#171614]/55 px-2 py-1">{article.field}</span></div></div><div className="flex min-h-[300px] flex-col justify-between p-6"><div><h2 className="font-serif text-3xl leading-[.96] tracking-[-.025em] transition-colors group-hover:text-[#C8472C]">{article.title}</h2><p className="mt-4 font-sans text-sm leading-6 text-[#171614]/60">{article.excerpt}</p></div><div className="mt-8 flex items-end justify-between border-t border-[#171614]/15 pt-4 font-sans text-[10px] uppercase tracking-[.12em] text-[#171614]/50"><span>{article.author}<br/><span className="text-[#171614]/40">{article.date}</span></span><span className="flex items-center gap-2"><span className="live-pulse"/> {article.views} views</span></div></div></article>)}</div></section>
    <section className="border-t border-[#171614]/15 bg-[#171614] px-6 py-16 text-[#F3F0E8] lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><div className="eyebrow !text-[#F3F0E8]/60"><span className="vermilion-dot"/> Keep reading</div><h2 className="mt-5 max-w-[570px] font-serif text-5xl leading-[.92]">The catalogue grows with the questions.</h2></div><a href="/about" className="button-vermilion">Read about the index <ArrowUpRight size={15}/></a></div></section>
    <footer className="border-t border-[#171614]/15 px-6 py-7 lg:px-12"><div className="mx-auto flex max-w-[1440px] justify-between font-sans text-[10px] uppercase tracking-[.13em] text-[#171614]/50"><span>© The Common Index</span><a href="/">Return home</a></div></footer>
  </main>;
}
