/*
 * The Reading Room: forum page as a calmer public square, keeping the same editorial markers
 * while making participation and account requirements explicit.
 */
import { ArrowUpRight, LockKeyhole, MessageCircle, Plus, Users } from "lucide-react";
import { useState } from "react";

const threads = [
  { tag: "Philosophy", title: "Can an unfinished idea still be useful?", author: "Riya M.", replies: 18, age: "2h ago" },
  { tag: "Technology", title: "What makes a digital space feel public?", author: "K. Baruah", replies: 31, age: "5h ago" },
  { tag: "Literature", title: "Which book changed the way you look at time?", author: "Aman D.", replies: 42, age: "1d ago" },
  { tag: "Gaming", title: "Are rules more creative than freedom?", author: "M. Saikia", replies: 11, age: "2d ago" },
];

export default function Forum() {
  const [accountOpen, setAccountOpen] = useState(false);
  return <main className="min-h-screen bg-[#F3F0E8] text-[#171614]"><header className="border-b border-[#171614]/15"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 lg:px-12"><a href="/" className="flex items-center gap-3"><img src="/manus-storage/common-index-mark_234d3c95.png" alt="" className="h-9 w-9 object-contain"/><span className="font-serif text-[21px] leading-none tracking-[-0.035em]">The Common Index</span></a><div className="flex items-center gap-5 font-sans text-[10px] font-semibold uppercase tracking-[0.14em]"><a href="/catalogue" className="hidden sm:block nav-link">Catalogue</a><a href="/club" className="hidden sm:block nav-link">Nagaon Club</a><button onClick={() => setAccountOpen(true)} className="button-ink">Create account <ArrowUpRight size={14}/></button></div></div></header>
    <section className="mx-auto max-w-[1440px] px-6 pb-14 pt-16 lg:px-12 lg:pb-20 lg:pt-24"><div className="grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><div className="eyebrow"><span className="vermilion-dot"/> The forum / open conversation</div><h1 className="mt-7 max-w-[760px] font-serif text-6xl leading-[.9] tracking-[-.055em] lg:text-8xl">A place to <em>think out loud.</em></h1></div><div className="border-l border-[#171614]/20 pl-6"><p className="font-sans text-sm leading-7 text-[#171614]/65">Come with a question. Stay for the complication. The forum is a member space for conversations that do not need to resolve themselves quickly.</p><button onClick={() => setAccountOpen(true)} className="button-vermilion mt-7">Join the conversation <ArrowUpRight size={15}/></button></div></div></section>
    <section className="border-y border-[#171614]/15 bg-[#EAE5DA] px-6 py-5 lg:px-12"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><div className="flex items-center gap-3 font-sans text-[10px] uppercase tracking-[0.14em] text-[#171614]/55"><Users size={15} className="text-[#C8472C]"/> 248 readers in the room</div><div className="font-sans text-[10px] uppercase tracking-[0.14em] text-[#171614]/50">Latest activity</div></div></section>
    <section className="mx-auto max-w-[1440px] px-6 py-14 lg:px-12 lg:py-20"><div className="grid gap-14 lg:grid-cols-[1fr_.34fr]"><div><div className="mb-6 flex items-center justify-between"><div className="eyebrow"><span className="vermilion-dot"/> Recent threads</div><button onClick={() => setAccountOpen(true)} className="hidden items-center gap-2 font-sans text-[10px] uppercase tracking-[0.12em] sm:flex">Start a thread <Plus size={14}/></button></div><div className="border-t border-[#171614]/20">{threads.map((thread) => <button onClick={() => setAccountOpen(true)} key={thread.title} className="group grid w-full gap-5 border-b border-[#171614]/20 py-7 text-left transition-colors hover:bg-[#EAE5DA] sm:grid-cols-[.18fr_1fr_.18fr] sm:px-4"><div className="font-sans text-[10px] uppercase tracking-[0.13em] text-[#C8472C]">{thread.tag}</div><div><h2 className="font-serif text-3xl leading-none tracking-[-.025em] transition-colors group-hover:text-[#C8472C]">{thread.title}</h2><p className="mt-3 font-sans text-[10px] uppercase tracking-[0.12em] text-[#171614]/50">{thread.author} <span className="mx-2 text-[#C8472C]">/</span> {thread.age}</p></div><div className="flex items-end justify-between font-sans text-[10px] uppercase tracking-[0.12em] text-[#171614]/50 sm:flex-col sm:items-end"><span className="inline-flex items-center gap-2"><MessageCircle size={13}/> {thread.replies}</span><ArrowUpRight size={17} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></div></button>)}</div></div><aside className="border-t border-[#171614]/20 pt-5"><div className="eyebrow"><span className="vermilion-dot"/> Before you post</div><p className="mt-6 font-serif text-3xl leading-none">Make room for another mind.</p><p className="mt-5 font-sans text-sm leading-6 text-[#171614]/60">The forum is account-only so every participant has a name, a place to return to, and a stake in the quality of the room.</p><button onClick={() => setAccountOpen(true)} className="mt-7 inline-flex items-center gap-2 font-sans text-[10px] font-semibold uppercase tracking-[0.13em] underline decoration-[#C8472C] decoration-2 underline-offset-8">Create your account <ArrowUpRight size={14}/></button></aside></div></section>
    <footer className="border-t border-[#171614]/15 px-6 py-7 lg:px-12"><div className="mx-auto flex max-w-[1440px] justify-between font-sans text-[10px] uppercase tracking-[0.13em] text-[#171614]/50"><span>© The Common Index / Forum</span><a href="/">Return home</a></div></footer>
    {accountOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#171614]/80 px-5" onClick={() => setAccountOpen(false)}><div className="w-full max-w-[480px] bg-[#F3F0E8] p-7 text-[#171614] lg:p-10" onClick={(event) => event.stopPropagation()}><div className="eyebrow"><LockKeyhole size={14} className="text-[#C8472C]"/> Account required</div><h2 className="mt-5 font-serif text-5xl leading-none">The room opens<br/><em>when you sign in.</em></h2><p className="mt-5 font-sans text-sm leading-6 text-[#171614]/60">Create an account or sign in to join threads, start discussions, and keep track of the ideas you care about. This front-end preview is ready for auth integration.</p><div className="mt-7 grid gap-3"><button className="button-vermilion justify-center">Create an account <ArrowUpRight size={14}/></button><button className="button-ink justify-center">Sign in <ArrowUpRight size={14}/></button></div><button className="mt-6 font-sans text-[10px] uppercase tracking-[0.13em] text-[#171614]/50 underline" onClick={() => setAccountOpen(false)}>Close</button></div></div>}
  </main>;
}
