/*
 * The Reading Room: homepage now behaves like a journal cover and current issue,
 * with the full catalogue moved to /catalogue and the latest work brought forward.
 */
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, ChevronRight, CircleArrowUp, Menu, X, Eye } from "lucide-react";
import { useState } from "react";

const latestArticles = [
  { id: "CI–014", title: "The politics of being unfinished", author: "Mara Voss", field: "Philosophy", excerpt: "On the ethical value of leaving a question open long enough for another mind to enter it.", views: "1,284", date: "18 Aug 2026" },
  { id: "CI–013", title: "Against frictionless reading", author: "Jon Bell", field: "Media", excerpt: "A small argument for difficulty, annotation, and the productive drag of a page that resists us.", views: "986", date: "12 Aug 2026" },
  { id: "CI–012", title: "The interface as a room", author: "Leila Okafor", field: "Technology", excerpt: "Digital spaces are not neutral containers. They instruct us in how to gather, speak, and stay.", views: "2,106", date: "05 Aug 2026" },
];

export default function Home() {
  // The useAuth hook provides authentication state.
  // To implement login/logout, call logout(), or start login from an event
  // handler: onClick={() => startLogin()} (imported from "@/const"). Never call
  // startLogin() during render (no href={startLogin()}) — it mints a one-time
  // nonce cookie and must run only at the moment of navigation.
  let { user, loading, error, isAuthenticated, logout } = useAuth();
  const latestQuery = trpc.catalogue.published.useQuery();
  const visibleLatest = latestQuery.data?.slice(0, 3).map((article) => ({ id: `CI–${String(article.id).padStart(3, "0")}`, title: article.title, author: article.authorName, field: article.category.name, excerpt: article.excerpt, views: article.viewCount.toLocaleString(), date: new Date(article.publishedAt ?? article.createdAt).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) })) ?? latestArticles;

  const [mobileOpen, setMobileOpen] = useState(false);
  return <main className="min-h-screen overflow-hidden bg-[#F3F0E8] text-[#171614]"><div className="paper-noise" aria-hidden="true" />
    <header className="relative z-10 border-b border-[#171614]/15"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 lg:px-12"><a className="flex items-center gap-3" href="/" aria-label="The Common Index home"><img src="/manus-storage/common-index-mark_234d3c95.png" alt="" className="h-9 w-9 object-contain"/><span className="font-serif text-[21px] leading-none tracking-[-0.035em]">The Common Index</span></a><nav className="hidden items-center gap-8 font-sans text-[10px] font-medium uppercase tracking-[0.14em] md:flex"><a className="nav-link" href="/about">About</a><a className="nav-link" href="/catalogue">Catalogue</a><a className="nav-link" href="/club">Nagaon Club</a><a className="nav-link" href="/forum">Forum</a><button onClick={() => user ? (window.location.href = "/admin") : startLogin()} className="font-sans text-[10px] font-semibold uppercase tracking-[.14em] underline decoration-[#C8472C] underline-offset-4">{user ? "Editorial desk" : "Sign in"}</button><a className="button-ink" href="/submit">Submit a paper <ArrowUpRight size={14}/></a></nav><button className="md:hidden" onClick={() => setMobileOpen(!mobileOpen)} aria-label={mobileOpen ? "Close menu" : "Open menu"}>{mobileOpen ? <X size={22}/> : <Menu size={22}/>}</button></div>{mobileOpen && <div className="border-t border-[#171614]/15 px-6 py-5 font-sans text-xs uppercase tracking-[0.14em] md:hidden"><a onClick={() => setMobileOpen(false)} className="block py-3" href="/about">About</a><a onClick={() => setMobileOpen(false)} className="block py-3" href="/catalogue">Catalogue</a><a onClick={() => setMobileOpen(false)} className="block py-3" href="/club">Nagaon Club</a><a onClick={() => setMobileOpen(false)} className="block py-3" href="/forum">Forum</a><button onClick={() => user ? (window.location.href = "/admin") : startLogin()} className="block py-3 text-left">{user ? "Editorial desk" : "Sign in"}</button><a className="button-ink mt-3" href="/submit">Submit a paper <ArrowUpRight size={14}/></a></div>}</header>
    <section id="top" className="relative mx-auto grid max-w-[1440px] grid-cols-1 gap-12 px-6 pb-20 pt-16 lg:grid-cols-[1.03fr_.97fr] lg:gap-16 lg:px-12 lg:pb-28 lg:pt-24"><div className="relative z-10 flex flex-col justify-between"><div><div className="eyebrow mb-8"><span className="vermilion-dot"/> An open index of serious ideas</div><h1 className="max-w-[760px] font-serif text-[clamp(3.8rem,8vw,8.4rem)] leading-[.88] tracking-[-.06em]">Ideas worth keeping <em>in circulation.</em></h1><p className="mt-9 max-w-[500px] font-sans text-[15px] leading-7 text-[#171614]/70">The Common Index is a publishing room for papers, essays, and working thoughts that move between disciplines. Read closely. Think outward.</p><div className="mt-9 flex flex-wrap items-center gap-5"><a href="#latest" className="button-vermilion">Read the latest <ChevronRight size={16}/></a><a href="/catalogue" className="inline-flex items-center gap-2 font-sans text-[11px] font-semibold uppercase tracking-[0.12em] underline decoration-[#C8472C] decoration-2 underline-offset-8 transition-transform duration-200 hover:translate-x-1">Explore the catalogue <ArrowUpRight size={14}/></a></div></div><div className="mt-16 flex items-end justify-between border-t border-[#171614]/20 pt-5 lg:mt-24"><p className="max-w-[280px] font-sans text-[11px] leading-5 text-[#171614]/60">For the curious, the exacting, and the generously unfinished.</p><span className="font-sans text-[11px] tracking-[0.14em] text-[#171614]/50">VOL. 01 / 2026</span></div></div><div className="relative min-h-[440px] lg:min-h-[640px]"><div className="absolute -right-16 -top-10 hidden font-serif text-[180px] leading-none text-[#C8472C]/10 lg:block">01</div><div className="relative h-full overflow-hidden border border-[#171614]/20 bg-[#DED8CA]"><img src="/manus-storage/common-index-hero_03007214.png" alt="Papers and a fountain pen on an archival desk" className="h-full min-h-[440px] w-full object-cover grayscale-[12%] transition-transform duration-700 hover:scale-[1.025] lg:min-h-[640px]"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-[#171614]/75 to-transparent px-6 pb-6 pt-28 text-[#F3F0E8]"><div><p className="eyebrow !text-[#F3F0E8]/75">On the desk</p><p className="mt-2 font-serif text-2xl">A place for the unfinished thought.</p></div><span className="font-sans text-[10px] uppercase tracking-[.15em]">Image / 001</span></div></div><span className="register-mark register-mark-top" aria-hidden="true"/><span className="register-mark register-mark-bottom" aria-hidden="true"/></div></section>
    <section id="latest" className="border-t border-[#171614]/15 bg-[#EAE5DA] px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><div className="mb-12 flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><div><div className="eyebrow"><span className="vermilion-dot"/> Newly published</div><div className="citation-mark mt-7"><span/><b>CI / 03</b></div><h2 className="mt-5 max-w-[530px] font-serif text-5xl leading-[.92] tracking-[-.045em] lg:text-7xl">The latest <em>from the room.</em></h2></div><a href="/catalogue" className="button-ink self-start sm:self-end">Explore all of the catalogue <ArrowUpRight size={14}/></a></div><div className="grid gap-5 lg:grid-cols-3">{visibleLatest.map((article, index) => <article key={article.id} className={`group flex min-h-[335px] flex-col justify-between border border-[#171614]/20 bg-[#F3F0E8] p-6 transition-transform duration-300 hover:-translate-y-1 ${index === 1 ? "lg:mt-8" : ""}`}><div className="flex items-start justify-between font-sans text-[10px] uppercase tracking-[0.13em] text-[#171614]/50"><span>{article.id} / {article.field}</span><ArrowUpRight size={16} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></div><div><h3 className="max-w-[340px] font-serif text-4xl leading-[.94] tracking-[-.03em] transition-colors group-hover:text-[#C8472C]">{article.title}</h3><p className="mt-4 max-w-[330px] font-sans text-sm leading-6 text-[#171614]/60">{article.excerpt}</p></div><div className="flex items-end justify-between border-t border-[#171614]/15 pt-4 font-sans text-[10px] uppercase tracking-[.12em] text-[#171614]/50"><span>{article.author} <span className="mx-1 text-[#C8472C]">/</span> {article.date}</span><span className="inline-flex items-center gap-1.5"><span className="live-pulse"/><Eye size={13}/> {article.views}</span></div></article>)}</div></div></section>
    <section className="mx-auto grid max-w-[1440px] gap-12 px-6 py-20 lg:grid-cols-[.75fr_1.25fr] lg:gap-24 lg:px-12 lg:py-28"><div><div className="eyebrow"><span className="vermilion-dot"/> More ways to gather</div><p className="mt-6 max-w-[290px] font-sans text-sm leading-7 text-[#171614]/60">The index is not only a place to publish. It is a place to meet, argue, and keep thinking in public.</p></div><div className="grid gap-5 sm:grid-cols-2"><a href="/club" className="group border border-[#171614]/20 bg-[#171614] p-7 text-[#F3F0E8] transition-transform hover:-translate-y-1"><div className="eyebrow !text-[#F3F0E8]/60"><span className="vermilion-dot"/> In Nagaon</div><h2 className="mt-16 font-serif text-4xl leading-[.94]">Debate & Discussion Club</h2><p className="mt-5 font-sans text-sm leading-6 text-[#F3F0E8]/60">A local room for public thought.</p><ArrowUpRight className="mt-8 text-[#C8472C]" size={20}/></a><a href="/forum" className="group border border-[#171614]/20 p-7 transition-transform hover:-translate-y-1"><div className="eyebrow"><span className="vermilion-dot"/> Online</div><h2 className="mt-16 font-serif text-4xl leading-[.94]">The Forum</h2><p className="mt-5 font-sans text-sm leading-6 text-[#171614]/60">A place to think out loud.</p><ArrowUpRight className="mt-8 text-[#C8472C]" size={20}/></a></div></section>
    <section id="about" className="border-t border-[#171614]/15 bg-[#F3F0E8] px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><div className="eyebrow"><span className="vermilion-dot"/> Why this room exists</div><h2 className="mt-6 max-w-[530px] font-serif text-5xl leading-[.92] tracking-[-.045em] lg:text-7xl">A place for ideas that are still <em>becoming.</em></h2></div><div className="max-w-[560px]"><p className="font-sans text-[16px] leading-8 text-[#171614]/70">We believe a serious idea should not have to arrive finished in order to deserve company. The Common Index is a public-minded room for careful reading, generous disagreement, and work that moves between disciplines.</p><a href="/about" className="mt-8 inline-flex items-center gap-2 font-sans text-[10px] font-semibold uppercase tracking-[.13em] underline decoration-[#C8472C] decoration-2 underline-offset-8">Read our vision <ArrowUpRight size={14}/></a></div></div></section>
    <section className="relative overflow-hidden bg-[#171614] px-6 py-20 text-[#F3F0E8] lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1fr_1.25fr] lg:items-end"><div><div className="eyebrow !text-[#F3F0E8]/60"><span className="vermilion-dot"/> For contributors</div><h2 className="mt-6 max-w-[570px] font-serif text-5xl leading-[.92] tracking-[-.05em] lg:text-7xl">Send the work.<br/><em>We’ll read it closely.</em></h2></div><div className="lg:pl-10"><p className="max-w-[500px] font-sans text-[15px] leading-7 text-[#F3F0E8]/65">Have a paper, essay, review, or working thought that wants a wider conversation? Email us a PDF or a link, along with a short note about the work.</p><a className="button-vermilion mt-8" href="/submit">submit@thecommonindex.org <ArrowUpRight size={16}/></a></div></div><div className="absolute -bottom-20 -right-5 font-serif text-[220px] leading-none text-[#F3F0E8]/[.035]">CI</div></section>
    <footer className="border-t border-[#171614]/15 bg-[#F3F0E8] px-6 py-7 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-5 font-sans text-[10px] uppercase tracking-[.13em] text-[#171614]/55 sm:flex-row"><span>© The Common Index / An independent publishing room</span><span>Made for ideas in motion <CircleArrowUp size={14} className="ml-2 inline text-[#C8472C]"/></span></div></footer>
  </main>;
}
